services:
  # ==========================================================
  # PostgreSQL Database Service
  # ==========================================================
  postgres:
    image: postgres:16
    container_name: pepsico-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=appd_ro
      - POSTGRES_PASSWORD=appd_pass
      - POSTGRES_DB=appd_licensing
      - TZ=America/New_York
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # SQL scripts run in alphabetical order
      # 01_ will seed dimensions first, then 02_ creates tables, then 03_ seeds sample data
      - ./sql/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    networks:
      - pepsico-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appd_ro -d appd_licensing"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ==========================================================
  # Grafana Visualization Service
  # ==========================================================
  grafana:
    image: grafana/grafana:12.2.1
    container_name: pepsico-grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - TZ=America/New_York
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "3000:3000"
    networks:
      - pepsico-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  # ==========================================================
  # ETL Services (AppDynamics & ServiceNow)
  # ==========================================================
  etl_appd:
    build:
      context: .
      dockerfile: docker/etl/Dockerfile
    container_name: pepsico-etl-appd
    restart: "no"
    command: ["/app/entrypoint.sh", "python", "scripts/etl/appd_etl.py"]
    env_file: .env
    environment:
      # Override DB_HOST for container networking
      - DB_HOST=postgres
      # Provide SSM_PATH for production secret fetching
      - SSM_PATH=${SSM_PATH:-/aspectiq/demo}
    volumes:
      - ./scripts:/app/scripts:ro
      - ./docker/etl:/app/docker/etl:ro
      - etl_logs:/var/log/etl
    networks:
      - pepsico-network
    depends_on:
      postgres:
        condition: service_healthy

  etl_snow:
    build:
      context: .
      dockerfile: docker/etl/Dockerfile
    container_name: pepsico-etl-snow
    restart: "no"
    command: ["/app/entrypoint.sh", "python", "scripts/etl/snow_etl.py"]
    env_file: .env
    environment:
      # Override DB_HOST for container networking
      - DB_HOST=postgres
      # Provide SSM_PATH for production secret fetching
      - SSM_PATH=${SSM_PATH:-/aspectiq/demo}
    volumes:
      - ./scripts:/app/scripts:ro
      - ./docker/etl:/app/docker/etl:ro
      - etl_logs:/var/log/etl
    networks:
      - pepsico-network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    name: pepsico_postgres_data
  grafana_data:
    name: pepsico_grafana_data
  etl_logs:
    name: pepsico_etl_logs

networks:
  pepsico-network:
    name: pepsico-network
    driver: bridge