version: '3.8'

services:
  # ==========================================================
  # PostgreSQL Database Service
  # ==========================================================
  postgres:
    image: postgres:16
    container_name: pepsico-postgres
    restart: unless-stopped
    environment:
      # These credentials are used by the PostgreSQL server itself.
      # The ETL scripts use the same values for local testing (from .env)
      - POSTGRES_USER=appd_ro
      - POSTGRES_PASSWORD=appd_pass
      - POSTGRES_DB=appd_licensing
      - TZ=America/New_York
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Volume to inject SQL schema setup scripts
      - ./sql/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    networks:
      - pepsico-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appd_ro -d appd_licensing"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ==========================================================
  # Grafana Visualization Service
  # ==========================================================
  grafana:
    image: grafana/grafana:12.2.1
    container_name: pepsico-grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - TZ=America/New_York
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    networks:
      - pepsico-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  # ==========================================================
  # ETL Services (AppDynamics & ServiceNow)
  # ==========================================================
  etl_appd:
    build:
      context: .
      dockerfile: docker/etl/Dockerfile
    container_name: pepsico-etl-appd
    restart: "no"
    command: ["/bin/bash", "/app/docker/etl/entrypoint.sh", "python", "scripts/etl/appd_etl.py"]
    # CRITICAL FIX: Explicitly load variables from .env to bypass automatic loading issues.
    env_file: .env
    volumes:
      - ./scripts:/app/scripts:ro
      - ./docker/etl:/app/docker/etl:ro
    networks:
      - pepsico-network
    depends_on:
      postgres:
        condition: service_healthy

  etl_snow:
    build:
      context: .
      dockerfile: docker/etl/Dockerfile
    container_name: pepsico-etl-snow
    restart: "no"
    command: ["/bin/bash", "/app/docker/etl/entrypoint.sh", "python", "scripts/etl/snow_etl.py"]
    # CRITICAL FIX: Explicitly load variables from .env to bypass automatic loading issues.
    env_file: .env
    volumes:
      - ./scripts:/app/scripts:ro
      - ./docker/etl:/app/docker/etl:ro
    networks:
      - pepsico-network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    name: pepsico_postgres_data
  grafana_data:
    name: pepsico_grafana_data

networks:
  pepsico-network:
    name: pepsico-network
    driver: bridge
