services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: appd_licensing
      POSTGRES_USER: appd_ro
      POSTGRES_PASSWORD: ChangeMe123!
    volumes:
      - ../postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - appd_net

  etl:
    build:
      context: ..
      dockerfile: docker/dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - appd_net

networks:
  appd_net:
    driver: bridge
