FROM python:3.12-slim

WORKDIR /app

# Copy and install dependencies
COPY docker/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application scripts
COPY scripts ./scripts

# Copy environment configuration
COPY docker/.env .env

# Default command
CMD ["python", "scripts/snow_etl.py"]
